default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: app
      password: b00king1o1
      host:     localhost

development:
  <<: *default
  database: bookings

test:
  <<: *default
  database: booking_test

production:
  <<: *default
  database: bookings_production